
on:
  push:
    
jobs:
  build:

    runs-on: subuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node index.js
